server:
  port: 9400

eureka:
  client: #Eureka server本身也是eureka的一个客户端，因为在集群下需要与其他eureka server进行数据的同步
    service-url:  # 定义eureka server url
      defaultZone: http://CloudEurekaServerA:9200/eureka,http://CloudEurekaServerB:9201/eureka
    register-with-eureka: true  #表示是否向Eureka中心注册自己的信息，默认为true
    fetch-registry: true #是否拉取Eureka server服务注册列表，默认为true
  instance:
    #    hostname: localhost #当前eureka实例的主机名
    #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        #git配置：uri、用户名、密码、分支
        git:
          uri: https://github.com/LY1009704526/springcloud.git # 配置git地址
          username: LY1009704526
          password: Ly13890649905
          search-paths:
            - springcloud
      label: main
  rabbitmq:
    host: 192.168.100.10
    port: 5672
    username: ly
    password: shine

#建议暴露所有的端口
management:
  endpoints:
    web:
      exposure:
        include: "*"

